FROM node:12-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# RUN npm install
# If you are building your code for production
RUN yarn install --prod

COPY . .

EXPOSE 3001

ENV NODE_ENV=production

CMD [ "node", "." ]
